### ISSUE TITLE
Fix "No handles with labels found to put in legend." warning

### ISSUE THREAD

**Issue by himaghna** [VlachosGroup/AIMSim#184]

**Comment by JacksonBurns** [comment]
The answer is probably [somewhere in this StackOverflow thread](https://stackoverflow.com/questions/64014746/how-do-you-create-a-legend-for-kde-plot-in-seaborn) but if this isn't actually disturbing any behavior and is an erroneous warning, we should just [ignore it in the code so that it doesn't annoy the uesr](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings).
