### ISSUE TITLE
```pip install aimsim``` not working on MacOSX

### ISSUE THREAD

**Issue by himaghna** [VlachosGroup/AIMSim#240]
Trace attached
[aimsim_macosx_installation_trace.txt](https://github.com/VlachosGroup/AIMSim/files/10582154/aimsim_macosx_installation_trace.txt)

System details:
Model Name:	MacBook Pro
Model Identifier: MacBookPro17,1
Chip: Apple M1
Total Number of Cores:	8 (4 performance and 4 efficiency)
Memory:	8 GB
System Firmware Version: 7429.81.3
OS Loader Version: 7429.81.3

**Comment by JacksonBurns** [comment]
From a cursory glance, this seems to be an [known issue with numpy](https://github.com/numpy/numpy/issues/17807#issuecomment-975689031) and has been fixed since version 1.21.4 -- unfortunately we have fixed out version of numpy to exactly 1.21.0. I will open a PR and experiment with allowing a wider range of numpy versions in particular.
